/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './app/**/*.{ts,tsx}',
    './components/**/*.{ts,tsx}',
    './lib/**/*.{ts,tsx}',
    './src/**/*.{ts,tsx}',
  ],
  theme: {
    extend: {
      fontFamily: {
        sans: ['Inter', 'system-ui', 'sans-serif'],
        headline: ['"Plus Jakarta Sans"', 'system-ui', 'sans-serif'],
        body: ['Inter', 'system-ui', 'sans-serif'],
      },
      colors: {
        bg: 'var(--color-bg)',
        surface: '#faf8ff',
        'surface-2': 'var(--color-surface-2)',
        'surface-3': 'var(--color-surface-3)',
        'surface-dim': '#d2d9f4',
        'surface-bright': '#faf8ff',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f2f3ff',
        'surface-container': '#eaedff',
        'surface-container-high': '#e2e7ff',
        'surface-container-highest': '#dae2fd',
        'surface-variant': '#dae2fd',
        'inverse-surface': '#283044',
        'inverse-on-surface': '#eef0ff',
        'on-surface': '#131b2e',
        'on-surface-variant': '#3e4947',
        outline: '#6e7977',
        'outline-variant': '#bdc9c6',

        border: 'var(--color-border)',
        'border-light': 'var(--color-border-light)',
        primary: '#005c55',
        'primary-container': '#0f766e',
        'on-primary': '#ffffff',
        'on-primary-container': '#a3faef',
        'primary-fixed': '#9cf2e8',
        'primary-fixed-dim': '#80d5cb',
        'on-primary-fixed': '#00201d',
        'on-primary-fixed-variant': '#00504a',
        'primary-light': 'var(--color-primary-light)',
        'primary-dark': 'var(--color-primary-dark)',

        secondary: '#4b41e1',
        'secondary-container': '#645efb',
        'on-secondary': '#ffffff',
        'on-secondary-container': '#fffbff',
        'secondary-fixed': '#e2dfff',
        'secondary-fixed-dim': '#c3c0ff',
        'on-secondary-fixed': '#0f0069',
        'on-secondary-fixed-variant': '#3323cc',

        tertiary: '#734700',
        'tertiary-container': '#945d00',
        'on-tertiary-container': '#ffe6cc',
        'tertiary-fixed': '#ffddb8',
        'tertiary-fixed-dim': '#ffb95f',
        'on-tertiary-fixed': '#2a1700',
        'on-tertiary-fixed-variant': '#653e00',

        error: '#ba1a1a',
        'error-container': '#ffdad6',
        'on-error': '#ffffff',
        'on-error-container': '#93000a',

        tx: 'var(--color-text)',
        'tx-2': 'var(--color-text-2)',
        'tx-3': 'var(--color-text-3)',
      },
      borderRadius: {
        '2xl': '1rem',
        '3xl': '1.25rem',
      },
    },
  },
  plugins: [],
};
